In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder

In [7]:
banknote_data = pd.read_csv("../Datasets/banknote.csv",sep=',')

In [8]:
banknote_data.head()

variance  skewness  kurtosis  entropy  authentic
0   3.62160    8.6661   -2.8073 -0.44699          0
1   4.54590    8.1674   -2.4586 -1.46210          0
2   3.86600   -2.6383    1.9242  0.10645          0
3   3.45660    9.5228   -4.0112 -3.59440          0
4   0.32924   -4.4552    4.5718 -0.98880          0

In [9]:
banknote_data= banknote_data.round()

In [10]:
banknote_data.head()

variance  skewness  kurtosis  entropy  authentic
0       4.0       9.0      -3.0     -0.0          0
1       5.0       8.0      -2.0     -1.0          0
2       4.0      -3.0       2.0      0.0          0
3       3.0      10.0      -4.0     -4.0          0
4       0.0      -4.0       5.0     -1.0          0

In [11]:
X = banknote_data.values[:,0:4]
Y = banknote_data.values[:,4]
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.2, random_state = 100)

In [12]:
from sklearn.neural_network import MLPClassifier

In [13]:
mlp = MLPClassifier(hidden_layer_sizes=(4),max_iter=50)

In [14]:
mlp.fit(X_train,Y_train)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=4, learning_rate='constant',
       learning_rate_init=0.001, max_iter=50, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [15]:
predictions = mlp.predict(X_test)

In [16]:
from sklearn.metrics import classification_report, confusion_matrix

In [17]:
predictions

array([1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0.,
       0., 0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 1., 0., 0., 1., 1., 0., 0., 1., 0.,
       1., 0., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 1.,
       1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 1., 1., 1.,
       0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 1., 1., 1., 0., 0., 1., 0., 1., 1.,
       0., 1., 0., 1., 0., 0., 0., 1., 1., 1., 0., 1., 1., 0., 0., 1., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 1., 1., 0., 1.,
       0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 1., 1.,
       0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 0., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 1.,
       0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 1., 0.,
       0., 1., 1., 0., 1.

In [18]:
if predictions.all() == Y_test.all():
    print("100%")

100%


In [19]:
print(confusion_matrix(Y_test,predictions))

[[145  18]
 [  1 111]]


In [20]:
print(classification_report(Y_test,predictions,target_names=['0','1']))

             precision    recall  f1-score   support

          0       0.99      0.89      0.94       163
          1       0.86      0.99      0.92       112

avg / total       0.94      0.93      0.93       275



In [21]:
print(mlp.predict_proba(X_test))

[[0.3730218  0.6269782 ]
 [0.96675116 0.03324884]
 [0.31767345 0.68232655]
 [0.97173556 0.02826444]
 [0.83390528 0.16609472]
 [0.88336059 0.11663941]
 [0.07500528 0.92499472]
 [0.9383735  0.0616265 ]
 [0.21241078 0.78758922]
 [0.91789972 0.08210028]
 [0.83679557 0.16320443]
 [0.39712012 0.60287988]
 [0.1541146  0.8458854 ]
 [0.90883801 0.09116199]
 [0.79589155 0.20410845]
 [0.98541169 0.01458831]
 [0.72056524 0.27943476]
 [0.99687006 0.00312994]
 [0.91647683 0.08352317]
 [0.94720662 0.05279338]
 [0.07997194 0.92002806]
 [0.43748741 0.56251259]
 [0.8530157  0.1469843 ]
 [0.12250725 0.87749275]
 [0.33014558 0.66985442]
 [0.42124786 0.57875214]
 [0.48628579 0.51371421]
 [0.13851426 0.86148574]
 [0.39452793 0.60547207]
 [0.38210868 0.61789132]
 [0.33014558 0.66985442]
 [0.98294501 0.01705499]
 [0.38454572 0.61545428]
 [0.98734265 0.01265735]
 [0.69853384 0.30146616]
 [0.78816809 0.21183191]
 [0.97919903 0.02080097]
 [0.39764211 0.60235789]
 [0.40846678 0.59153322]
 [0.32583959 0.67416041]


In [22]:
mlp = MLPClassifier(hidden_layer_sizes=(4),max_iter=100000)
mlp.fit(X_train,Y_train)
predictions = mlp.predict(X_test)

In [23]:
print(confusion_matrix(Y_test,predictions))

[[160   3]
 [  0 112]]


In [24]:
print(classification_report(Y_test,predictions,target_names=['0','1']))

             precision    recall  f1-score   support

          0       1.00      0.98      0.99       163
          1       0.97      1.00      0.99       112

avg / total       0.99      0.99      0.99       275

